export const ADD_MESSAGE = 'ADD_MESSAGE';
export const REMOTE_MESSAGE = 'REMOTE_MESSAGE';
export const CHANGE_USER_NAME = 'CHANGE_USER_NAME';
export const CHANGE_USER_COLOR = 'CHANGE_USER_COLOR';
export const FRAME_UPDATE = 'FRAME_UPDATE';
export const SHOW_OPTIONS = 'SHOW_OPTIONS';
export const SOCKET_CONNECTED = 'SOCKET_CONNECTED';
export const SOCKET_DISCONNECTED = 'SOCKET_DISCONNECTED';
